//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKho
    {
        public int STT { get; set; }
        public string ID_ThietBi { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual KHO KHO { get; set; }
    }
}
